import Link from 'next/link';
import {ArrowUpRight,ArrowRight,BookOpen,Code2,Layers,BrainCircuit,MapPin} from 'lucide-react';
import {personal,projects} from '@/lib/portfolio';
import {books,articles} from '@/lib/editorial';
import {ProjectCard,SectionTitle,ArticleCard,ResumeActions,TechLogo} from '@/components/portfolio-ui';
import {SocialLinks} from '@/components/site-shell';
export default function Home(){return <main id="main" tabIndex={-1} className="home-page"><section className="home-hero wrap"><div className="hero-copy"><div className="hero-label"><span/>FULL-STACK · REACT NATIVE</div><p className="hello">Hello, I’m Harsha Akasam.</p><h1>Thoughtful code.<br/><span>Useful experiences.</span></h1><p className="hero-description">{personal.intro}</p><div className="hero-cta"><Link className="button primary" href="/work">Explore my work<ArrowUpRight size={18}/></Link><Link className="button secondary" href="/about">More about me<ArrowRight size={18}/></Link></div><SocialLinks/><div className="hero-stack"><span>MY EVERYDAY TOOLKIT</span>{['React.js','React Native','Node.js','Python','MongoDB'].map(n=><span title={n} key={n}><TechLogo name={n}/><span className="sr-only">{n}</span></span>)}</div></div><div className="hero-profile"><span className="portrait-edition" aria-hidden="true">THE PERSON BEHIND THE CODE</span><div className="profile-image"><img className="portrait-day" src="/assets/harsha-outdoors.jpg" alt="Harsha Akasam outdoors in the hills" fetchPriority="high"/><div className="profile-image-caption"><span>HARSHA AKASAM</span><p>Software Developer</p></div></div><div className="profile-location"><MapPin size={16}/> Kakinada, India <span>01 / THE DEVELOPER</span></div><div className="profile-note"><Code2 size={22}/><div>From an idea<small>to a working product.</small></div></div></div></section>
 <div className="focus-strip wrap">{[{icon:Code2,title:'Frontend & mobile',detail:'Interfaces that feel intuitive.'},{icon:Layers,title:'Full-stack systems',detail:'Connecting the pieces that matter.'},{icon:BrainCircuit,title:'AI & machine learning',detail:'Exploring more thoughtful software.'}].map(c=><div key={c.title}><c.icon size={23}/><div><h2>{c.title}</h2><p>{c.detail}</p></div></div>)}</div>
 <section className="section wrap"><SectionTitle label="SELECTED WORK" title="Built with purpose." href="/work" link="View all projects"/><div className="project-grid">{['job-align','cognitive-compass'].map(slug=><ProjectCard key={slug} project={projects.find(p=>p.slug===slug)!}/>)}</div></section>
 <section className="learning-section" id="learning"><div className="wrap section"><SectionTitle label="KEEPING CURIOSITY ALIVE" title="Books & Learning"/><div className="learning-layout"><div className="learning-intro"><BookOpen size={34}/><h3>There’s always<br/>more to understand.</h3><p>A reading shelf for the ideas behind the code—from JavaScript fundamentals to intelligent systems.</p><span className="status-label">SUGGESTED READING</span><p className="meta">Selected for relevance to these projects. Reading completion is not recorded.</p></div><div className="reading-list">{books.map((b,i)=><a key={b.title} href={b.url} target="_blank" rel="noopener noreferrer"><span className="reading-number">0{i+1}</span><div><span className="meta">{b.topic}</span><h3>{b.title}</h3><p>{b.author}</p><p className="book-description">{b.description}</p></div><ArrowUpRight size={20}/></a>)}</div></div></div></section>
 <section className="section wrap"><SectionTitle label="IDEAS & EXPLORATIONS" title="From the blog." href="/blogs" link="Browse articles"/><div className="article-grid">{articles.map((a,i)=><ArticleCard article={a} index={i} key={a.slug}/>)}</div></section><section className="resume-section wrap" id="resume"><div><p className="eyebrow">A LITTLE MORE CONTEXT</p><h2>The experience behind the work.</h2><p>My skills, education, internships, and project highlights in one place.</p></div><ResumeActions/></section></main>}
