'use client';
import {useEffect,useState,useRef} from 'react';
import {ArrowUpRight,RefreshCw,Code2,GitBranch,Terminal,BookOpen,Braces} from 'lucide-react';
import {profiles} from '@/lib/portfolio';
import type {PlatformStat} from '@/lib/coding-stats';
import snapshot from '@/lib/coding-snapshot.json';
const ids=['github','leetcode','codechef','geeksforgeeks','hackerrank'];
export function CodingDashboard(){
 const [stats,setStats]=useState<Record<string,PlatformStat>>(snapshot as Record<string,PlatformStat>),[selected,setSelected]=useState('leetcode'),[busy,setBusy]=useState(false);const running=useRef(false);
 async function refresh(){if(running.current)return;running.current=true;setBusy(true);try{await Promise.all(ids.map(async id=>{try{const r=await fetch('/api/coding-stats?platform='+id,{cache:'no-store',signal:AbortSignal.timeout(15000)});if(!r.ok)throw Error();const data=await r.json() as PlatformStat;setStats(old=>({...old,[id]:data.status==='unavailable'&&old[id]?.value!=null?{...old[id],status:'cached',note:data.note}:data}));}catch{setStats(old=>({...old,[id]:old[id]?{...old[id],status:'cached',note:'Refresh unavailable. Try again later.'}:{platform:id,label:id==='github'?'Public repositories':'Problems solved',value:null,status:'unavailable',checkedAt:null,details:[],note:'Unable to reach this platform.'}}))}}))}finally{setBusy(false);running.current=false}}
 useEffect(()=>{void refresh();const t=setInterval(()=>{if(!document.hidden)void refresh()},60000);const onFocus=()=>void refresh();window.addEventListener('focus',onFocus);return()=>{clearInterval(t);window.removeEventListener('focus',onFocus)}},[]);
 const p=profiles[ids.indexOf(selected)],data=stats[selected];const known=['leetcode','codechef','geeksforgeeks'].filter(id=>stats[id]?.value!=null);
 const activity=stats.leetcode?.activity||{};const days=Array.from({length:91},(_,i)=>{const d=new Date();d.setUTCHours(0,0,0,0);d.setUTCDate(d.getUTCDate()-90+i);const key=String(Math.floor(d.getTime()/1000));return {date:d.toISOString().slice(0,10),count:activity[key]||0}});
 return <section className="coding-dashboard" aria-label="Coding platform statistics"><div className="stats-toolbar"><div><strong>{known.reduce((sum,id)=>sum+(stats[id].value||0),0).toLocaleString()}</strong><span>Reported problems solved across {known.length} platforms</span><small>Platform totals may include the same problem. Unavailable platforms are excluded.</small></div><button className="button secondary" disabled={busy} onClick={refresh}><RefreshCw size={16} className={busy?'spin':''}/>{busy?'Refreshing…':'Refresh stats'}</button></div><div className="dashboard-layout"><nav className="platform-selector" aria-label="Select Platform"><h2>Select Platform</h2>{profiles.map((p,i)=>{const Icon=[GitBranch,Code2,Terminal,BookOpen,Braces][i];return <button aria-pressed={selected===ids[i]} className={selected===ids[i]?'selected':''} key={p.name} onClick={()=>setSelected(ids[i])}><Icon size={20}/><span>{p.name}<small>{stats[ids[i]]?.value==null?'Not available':`${stats[ids[i]].value} ${stats[ids[i]].label.toLowerCase()}`}</small></span></button>})}</nav><div className="platform-detail" aria-live="polite"><div className="platform-detail-heading"><div><p className="eyebrow">@{p.handle}</p><h2>{p.name}</h2></div><a className="text-link" href={p.url} target="_blank" rel="noopener noreferrer">View profile<ArrowUpRight size={16}/></a></div><div className="stat-total"><strong>{data?.value==null?'—':data.value.toLocaleString()}</strong><span>{data?.label||'Problems solved'}</span></div><div className="stat-breakdown">{data?.details.map(d=><div key={d.label}><strong>{d.value}</strong><span>{d.label}</span></div>)}</div><p className="meta">{data?.checkedAt?`${data.status==='updated'?'Updated':'Last verified'} ${new Date(data.checkedAt).toISOString().slice(0,16).replace('T',' ')+' UTC'}`:'No verified count available.'}</p>{data?.note&&<p className="stat-note">{data.note}</p>}</div></div><p className="meta">Refreshes on page load, when you return to this tab, and every minute while this page is visible.</p><section className="activity-section"><h2>Submission Activity</h2><p>LeetCode · Last 13 weeks · Accepted and attempted submissions, not unique problems.</p>{stats.leetcode?.activity!==undefined?<><div className="activity-grid" aria-label="Daily LeetCode submissions">{days.map(d=><span tabIndex={0} key={d.date} title={`${d.date}: ${d.count} submissions`} aria-label={`${d.date}: ${d.count} submissions`} data-level={d.count===0?0:d.count<3?1:d.count<6?2:3}/>)}</div><div className="activity-legend"><span>Less</span>{[0,1,2,3].map(n=><i key={n} data-level={n}/>)}<span>More</span></div></>:<p className="stat-note">Activity will appear when LeetCode returns its submission calendar.</p>}</section></section>
}
