'use client';
import {useState} from 'react';
import Link from 'next/link';
import {ArrowUpRight,ArrowRight,Download,FileText,BookOpen,Code2,Layers,Compass,Route,Check,Copy} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {personal,certifications,type Project} from '@/lib/portfolio';
import {logoNames,type Article} from '@/lib/editorial';
export function PageIntro({label,title,description}:{label:string;title:string;description:string}){return <header className="page-intro"><p className="eyebrow">{label}</p><h1>{title}</h1><p>{description}</p></header>}
export function SectionTitle({label,title,href,link='Explore more'}:{label:string;title:string;href?:string;link?:string}){return <div className="section-title"><div><p className="eyebrow">{label}</p><h2>{title}</h2></div>{href&&<Link prefetch={true} href={href} className="text-link">{link}<ArrowUpRight size={17}/></Link>}</div>}
export function TechLogo({name}:{name:string}){const logo=logoNames[name];return <span className={'tech-logo '+(logo==='express'?'mono-logo':'')}>{logo?<img src={'/logos/'+logo+'.svg'} alt="" width={28} height={28} loading="lazy"/>:<Code2 size={25} aria-hidden="true"/>}</span>}
export function ProjectCard({project:p,priority=false}:{project:Project;priority?:boolean}){const Icon=p.slug==='job-align'?Route:p.slug==='infrastructure-tracker'?Layers:Compass;return <article className="project-card"><Link prefetch={true} href={'/projects/'+p.slug} className={'project-cover '+p.slug} aria-label={'Explore '+p.name}>{p.cover?<img src={p.cover} alt={p.coverAlt||p.name+' concept illustration'} width={1536} height={1024} loading={priority?'eager':'lazy'} decoding="async" fetchPriority={priority?'high':'auto'}/>:p.image?<img src={p.image} alt="Cognitive Compass interface from the final-review presentation" loading="lazy"/>:<div className="project-wordmark"><Icon size={36}/><span>{p.name}</span><small>{p.slug==='job-align'?'MOBILE APPLICATION':p.slug==='infrastructure-tracker'?'ASSET MANAGEMENT':'FRONTEND REPOSITORY'}</small></div>}{p.cover&&<span className="cover-caption">Concept artwork</span>}<span className="cover-arrow"><ArrowUpRight size={22}/></span></Link><div className="project-body"><div className="meta-line"><span>{p.category}</span><span>{p.year||'Project repository'}</span></div><Link prefetch={true} href={'/projects/'+p.slug}><h3>{p.name}</h3></Link><p>{p.tagline}</p><div className="tags">{p.stack.slice(0,4).map(t=><span key={t}>{t}</span>)}</div></div></article>}
export function ArticleCard({article:a,index=0}:{article:Article;index?:number}){return <article className="article-card"><Link prefetch={true} href={'/blogs/'+a.slug}><div className={'article-graphic article-tone-'+index}><span>FIELD NOTES</span><strong>0{index+1}</strong><BookOpen size={30}/></div><div className="article-card-copy"><p className="eyebrow">{a.category}</p><h3>{a.title}</h3><p>{a.summary}</p><span className="text-link">Read article <ArrowRight size={17}/></span></div></Link></article>}
export function ResumeActions(){const [open,setOpen]=useState(false);return <><div className="resume-actions"><button onClick={()=>setOpen(true)} className="button primary"><FileText size={18}/>View résumé</button><a href={personal.resume} download="Harsha-Akasam-Resume.pdf" className="button secondary"><Download size={18}/>Download PDF</a></div><Dialog open={open} onOpenChange={setOpen}><DialogContent className="document-dialog"><DialogTitle>{personal.name} · Résumé</DialogTitle><DialogDescription>Experience, skills, education, and projects.</DialogDescription><iframe src={personal.resume} title="Harsha Akasam résumé"/><a className="text-link" href={personal.resume} target="_blank" rel="noopener noreferrer">Open PDF in a new tab <ArrowUpRight size={17}/></a></DialogContent></Dialog></>}
export function CredentialGrid(){const [active,setActive]=useState<(typeof certifications)[number]|null>(null);return <><div className="credential-grid">{certifications.map((c,i)=><button className="credential-card" key={c.title} onClick={()=>setActive(c)}><div className={'issuer-logo issuer-'+i}>{i===0?'ORACLE':i===1?'C':'IT'}<span>{i===0?'UNIVERSITY':i===1?'ESSENTIALS':'SPECIALIST'}</span></div><div><p className="meta">{c.issuer}</p><h3>{c.title}</h3><p className="meta">{c.date}</p></div><ArrowUpRight size={19}/></button>)}</div><Dialog open={!!active} onOpenChange={v=>{if(!v)setActive(null)}}><DialogContent className="document-dialog"><DialogTitle>{active?.title}</DialogTitle><DialogDescription>{active?.issuer} · {active?.date}</DialogDescription>{active&&(active.file.endsWith('.pdf')?<iframe src={active.file} title={active.title}/>:<img src={active.file} alt={active.title+' certificate'}/>)}{active&&<a className="text-link" href={active.file} target="_blank" rel="noopener noreferrer">Open certificate <ArrowUpRight size={16}/></a>}</DialogContent></Dialog></>}
export function CopyEmail(){const [copied,setCopied]=useState(false);return <button className="copy-email" onClick={async()=>{try{await navigator.clipboard.writeText(personal.email);setCopied(true);setTimeout(()=>setCopied(false),2000)}catch{location.href='mailto:'+personal.email}}}>{copied?<Check size={16}/>:<Copy size={16}/>}<span aria-live="polite">{copied?'Copied':'Copy email'}</span></button>}
