 'use client';
import {useEffect,useState,useRef} from 'react';
import Link from 'next/link';
import {usePathname,useRouter} from 'next/navigation';
import {ArrowUpRight,Menu,X,Send,Sparkles,Code2,BriefcaseBusiness} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {personal,sections} from '@/lib/portfolio';
import {answerQuestion,isPortfolioRoute,type Reply} from '@/lib/jarvis';
import {CopyEmail} from '@/components/portfolio-ui';
export function External({href,children,className=''}:{href:string;children:React.ReactNode;className?:string}){return <a href={href} target="_blank" rel="noopener noreferrer" className={className}>{children}</a>}
export function SiteShell({children}:{children:React.ReactNode}){
 const pathname=usePathname(),router=useRouter();const [menu,setMenu]=useState(false),[jarvis,setJarvis]=useState(false),[progress,setProgress]=useState(0);
 useEffect(()=>{let frame=0;const scroll=()=>{if(frame)return;frame=requestAnimationFrame(()=>{const h=document.documentElement.scrollHeight-innerHeight;setProgress(h?scrollY/h*100:0);frame=0})};window.addEventListener('scroll',scroll,{passive:true});scroll();return()=>{window.removeEventListener('scroll',scroll);cancelAnimationFrame(frame)}},[]);


 function jump(href:string){setMenu(false);if(href.includes('#')&&href.split('#')[0]===pathname){location.hash=href.split('#')[1]}else router.push(href);}
 return <><a className="skip-link" href="#main">Skip to content</a><div className="reading-progress" style={{width:progress+'%'}}/>
 <header className="site-header"><Link className="brand" href="/" aria-label="Harsha Akasam home"><span className="brand-mark">ha<span>.</span></span><span className="brand-name">Harsha Akasam<small>SOFTWARE DEVELOPER</small></span></Link><nav aria-label="Main navigation" className="desktop-nav">{sections.map(([href,label])=><Link prefetch={true} href={href} key={href} aria-current={pathname===href?'page':undefined} className={pathname===href?'current':''}>{label}</Link>)}</nav><div className="nav-actions"><button className="mobile-menu" aria-label="Open navigation" onClick={()=>setMenu(true)}><Menu/></button></div></header>
 <div className="page-content">{children}</div>
 <section className="contact-banner wrap" id="contact"><div><p className="eyebrow">LET’S CONNECT</p><h2>Good work starts with<br/>a conversation.</h2><a className="email-link" href={'mailto:'+personal.email}>{personal.email}<ArrowUpRight size={22}/></a><CopyEmail/></div><div className="contact-side"><p>Have a project, an opportunity,<br/>or an interesting idea?</p><SocialLinks/></div></section>
 <footer className="footer wrap"><Link className="brand-mark" href="/">ha<span>.</span></Link><p>Built with curiosity. Refined with care.</p><span>© {new Date().getFullYear()} {personal.name}</span><a href="#main">Back to top ↑</a></footer>
 <button className="jarvis-launcher" onClick={()=>setJarvis(true)} aria-label="Open Jarvis portfolio assistant"><Sparkles size={20}/><span>Ask Jarvis</span><ArrowUpRight size={15}/></button>
 <Dialog open={menu} onOpenChange={setMenu}><DialogContent className="menu-dialog"><DialogTitle>Explore the portfolio</DialogTitle><DialogDescription>Work, ideas, and the journey behind them.</DialogDescription>{sections.map(([href,label])=><button key={href} onClick={()=>jump(href)}>{label}<ArrowUpRight size={18}/></button>)}</DialogContent></Dialog>

 <Jarvis open={jarvis} onOpenChange={setJarvis} context={pathname.startsWith('/projects/')?pathname.split('/')[2]:pathname} navigate={jump}/></>
}
function Jarvis({open,onOpenChange,context,navigate}:{open:boolean;onOpenChange:(v:boolean)=>void;context:string;navigate:(h:string)=>void}){
 const [messages,setMessages]=useState<{role:'user'|'assistant';text:string;actions?:Reply['actions']}[]>([{role:'assistant',text:'Hello, I’m Jarvis. Ask me about Harsha’s work and I’ll open the relevant page and explain it. Try: ‘Jarvis, which projects has he worked on?’'}]);const [input,setInput]=useState(''),[busy,setBusy]=useState(false);const end=useRef<HTMLDivElement>(null);
 useEffect(()=>{end.current?.scrollIntoView({block:'nearest'})},[messages,busy,open]);
 async function ask(question:string){if(busy||!question.trim())return;setInput('');setMessages(m=>[...m,{role:'user',text:question}]);setBusy(true);let result:Reply;try{const res=await fetch('/api/jarvis',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:question,context}),signal:AbortSignal.timeout(6000)});if(!res.ok)throw Error();result=await res.json();if(typeof result.text!=='string')throw Error();}catch{result=answerQuestion(question,context)}setMessages(m=>[...m,{role:'assistant',...result}]);if(result.navigateTo&&isPortfolioRoute(result.navigateTo))navigate(result.navigateTo);setBusy(false)}
 if(!open)return null;
 return <aside className="jarvis-panel" aria-label="Jarvis website guide"><button className="jarvis-close" onClick={()=>onOpenChange(false)} aria-label="Close Jarvis"><X size={20}/></button><div className="jarvis-heading"><div className="jarvis-emblem"><Sparkles size={25}/></div><div><h2>Jarvis<span> / Website guide</span></h2><p>Ask, explore, understand.</p></div></div><div className="chat-messages" role="log" aria-live="polite" aria-label="Conversation">{messages.map((m,i)=><div className={'message '+m.role} key={i}><small>{m.role==='user'?'YOU':'Jarvis'}</small><p>{m.text}</p>{m.actions&&<div className="answer-actions">{m.actions.map(a=><a href={a.href} key={a.href} onClick={e=>{if(a.href.startsWith('/')&&!a.href.startsWith('/assets/')){e.preventDefault();onOpenChange(false);navigate(a.href)}}} target={a.href.startsWith('http')||a.href.startsWith('/assets/')?'_blank':undefined} rel="noopener noreferrer">{a.label}<ArrowUpRight size={14}/></a>)}</div>}</div>)}{busy&&<p className="typing">Jarvis is finding the relevant information…</p>}<div ref={end}/></div><div className="quick-prompts">{['Which projects has he worked on?','Explain Job Align','Show his skills','Open Practice'].map(q=><button disabled={busy} onClick={()=>ask(q)} key={q}>{q}</button>)}</div><form onSubmit={e=>{e.preventDefault();ask(input)}} className="chat-form"><label className="sr-only" htmlFor="jarvis-input">Ask about Harsha</label><input id="jarvis-input" value={input} onChange={e=>setInput(e.target.value)} maxLength={1500} placeholder="Ask about Harsha or his work…" autoComplete="off"/><button disabled={busy||!input.trim()} aria-label="Send question"><Send size={19}/></button></form><p className="chat-note">Commands open portfolio pages. Answers use documented portfolio content.</p></aside>
}
export function SocialLinks(){return <div className="social-links"><External href={personal.github}><Code2 size={18}/> GitHub <ArrowUpRight size={14}/></External><External href={personal.linkedin}><BriefcaseBusiness size={18}/> LinkedIn <ArrowUpRight size={14}/></External></div>}
