export const books=[
 {title:'Eloquent JavaScript',author:'Marijn Haverbeke',topic:'JavaScript',description:'A practical foundation in the language, browser programming, and Node.js.',url:'https://eloquentjavascript.net/'},
 {title:'You Don’t Know JS Yet',author:'Kyle Simpson',topic:'Language fundamentals',description:'A closer look at JavaScript’s core mechanisms, scope, and closures.',url:'https://github.com/getify/You-Dont-Know-JS'},
 {title:'Dive into Deep Learning',author:'Aston Zhang, Zachary C. Lipton, Mu Li & Alexander J. Smola',topic:'AI & machine learning',description:'An interactive introduction to deep learning through explanations and executable examples.',url:'https://d2l.ai/'}
];
export type Article={slug:string;title:string;category:string;project:string;summary:string;intro:string;sections:{title:string;paragraphs:string[];code?:string}[];sources:{label:string;url:string}[]};
export const articles:Article[]=[
 {slug:'reliable-mobile-api-experiences',title:'The API is only half the mobile experience.',category:'Mobile engineering',project:'job-align',summary:'Designing loading, empty, error, and success states for a job-discovery application.',intro:'A job listing screen can make a successful network request and still feel unreliable. What the visitor sees before the response arrives, after it fails, or when it contains no results is just as important as the request itself. A project like Job Align is a useful setting for exploring these decisions.',sections:[
 {title:'Start with the states a person can actually encounter',paragraphs:['Treat the screen as a small set of explicit states: loading, results, empty, and error. Empty is a successful response with no matching jobs; error means the application could not complete the request. Giving both the same message makes it harder for a visitor to know what to do next.','Write the messages alongside the interface. “No jobs match these filters” should offer a way to reset the filters. “We couldn’t load the jobs” should offer a retry. A loading indicator should communicate that something is happening without blocking unrelated navigation.']},
 {title:'Keep networking outside the presentation',paragraphs:['React Native provides the Fetch API for network requests. Its documentation also explains asynchronous handling and platform networking considerations. A small service function can give the interface a consistent result without scattering endpoint details across components.','The example below illustrates a boundary, rather than code taken from Job Align. A production implementation should also validate the returned data before the interface consumes it.'],code:"async function loadJobs(signal: AbortSignal) {\n  const response = await fetch('/api/jobs', { signal });\n  if (!response.ok) throw new Error('Jobs unavailable');\n  return response.json();\n}"},
 {title:'Protect the visitor’s intent',paragraphs:['Imagine someone changes a filter while an earlier request is still pending. The older response should not overwrite the newer selection. Canceling obsolete requests or comparing request identifiers helps keep the displayed results aligned with the latest action.','Caching can make returning to a listing feel faster, but the interface should still make freshness understandable. Preserve the selected filters and scroll position where practical. Test slow connections and repeated actions, not just the first successful request.']}
 ],sources:[{label:'React Native: Networking',url:'https://reactnative.dev/docs/network'}]},
 {slug:'designing-a-clear-asset-dashboard',title:'Give complex inventory a clear structure.',category:'Frontend architecture',project:'infrastructure-tracker',summary:'A practical approach to building, floor, and room views without duplicating application state.',intro:'An infrastructure dashboard has to answer two different questions: “Where is this asset?” and “What is in this room?” Infrastructure Tracker’s documented building, floor, and room hierarchy makes it a useful example of how information architecture shapes a frontend.',sections:[
 {title:'Model the asset once',paragraphs:['A fan or a desk does not become a different asset when someone switches views. Give the record a stable identifier and represent its location with references to its building, floor, and room. This makes it possible to show the same record in multiple views without maintaining separate copies.','React’s guidance on state structure recommends avoiding redundant and duplicated state. For a dashboard, the selected room and search query can be state, while the visible list can be derived from the current records.']},
 {title:'Separate filters from the underlying records',paragraphs:['Store the visitor’s filter choices explicitly. Derive the displayed assets from those choices instead of creating a second inventory array that must be kept synchronized. This makes resetting filters, changing rooms, and combining search terms easier to reason about.','This simplified example illustrates the idea. A larger inventory may need server-side filtering, pagination, and a more deliberate search strategy.'],code:"const visibleAssets = assets.filter(asset => {\n  const inRoom = !roomId || asset.roomId === roomId;\n  const matches = asset.name.toLowerCase()\n    .includes(query.trim().toLowerCase());\n  return inRoom && matches;\n});"},
 {title:'Make the hierarchy visible',paragraphs:['A breadcrumb such as Building A / Floor 2 / Room 204 gives the visitor a way to understand and change the current scope. When a filter removes every result, keep that context visible and offer a reset.','An overview can prioritize quantity and location, while a detail view provides warranty, manufacturer, and usage information. The project README documents those asset details; the broader design lesson is to reveal information where it helps a decision, rather than presenting every field at once.']}
 ],sources:[{label:'React: Choosing the State Structure',url:'https://react.dev/learn/choosing-the-state-structure'},{label:'Infrastructure Tracker: project README',url:'https://github.com/HarshaAkasam/Infrastructure_Tracker/blob/main/README.md'}]},
 {slug:'agents-that-help-people-think',title:'Design AI agents that help people think.',category:'AI & systems',project:'cognitive-compass',summary:'Separating routing, interpretation, framework selection, and synthesis in a decision-support system.',intro:'A useful decision-support assistant should help a person examine a choice without pretending to know the right answer for their life. Cognitive Compass, a final-year team project, explores this space through structured decision signals and multiple agent roles. Its review presentation provides the context for the design discussion below.',sections:[
 {title:'Give each stage a clear responsibility',paragraphs:['The presentation distinguishes ordinary conversation from queries that call for deeper decision analysis. That separation matters: a greeting should not trigger a long reasoning workflow, and a complex trade-off deserves more than a generic reply.','The ADK documentation distinguishes model-driven agents, workflow agents, and custom agents. Those categories help describe different control needs, but adding more agents does not automatically improve the result. Start with responsibilities and handoff contracts.']},
 {title:'Use structure where repeatability matters',paragraphs:['Cognitive Compass’s presentation describes a framework matcher that scores candidate frameworks from decision signals. That is different from asking a model to freely invent the next framework. A repeatable selection rule can make it easier to explain why a particular reasoning lens was chosen.','Keep the signals, selected framework, and generated answer separate. If the result is unhelpful, the team can then inspect whether the query was misunderstood, the framework was poorly matched, or the synthesis failed to reflect the available context. This is a design benefit, not a claim of measured project accuracy.']},
 {title:'Keep the person in control',paragraphs:['A useful response can organize options, name uncertainties, describe trade-offs, and offer a manageable next step. It should not disguise assumptions as facts or treat a generated answer as the person’s final decision.','Evaluation should include ambiguous prompts, missing information, follow-up corrections, and requests outside the assistant’s scope. The system should be able to ask a clarifying question or acknowledge a limit. Clear boundaries are part of the experience, just like the conversation interface itself.']}
 ],sources:[{label:'Google ADK: Agents',url:'https://adk.dev/agents/'},{label:'Project context: Cognitive Compass final-review presentation supplied by Harsha',url:'/projects/cognitive-compass'}]}
];
export const logoNames:Record<string,string>={'React.js':'react','React Native':'react','JavaScript':'javascript','TypeScript':'typescript','Python':'python','Node.js':'nodejs','Express.js':'express','MongoDB':'mongodb','HTML5':'html5','CSS3':'css3','Java':'java','Git':'git','MySQL':'mysql','C++':'cplusplus','C':'c','NumPy':'numpy','Pandas':'pandas'};
export const proficiency=[
 {area:'Frontend development',status:'Applied in projects',detail:'React interfaces, responsive layouts, filtering, and reusable components.',tech:['React.js','JavaScript','HTML5','CSS3'],evidence:'/projects/infrastructure-tracker'},
 {area:'Mobile development',status:'Applied in projects',detail:'React Native screens, navigation, and connected job-discovery flows.',tech:['React Native','JavaScript'],evidence:'/projects/job-align'},
 {area:'Backend & data',status:'Applied in projects',detail:'REST APIs and connected application data with Express and MongoDB.',tech:['Node.js','Express.js','MongoDB'],evidence:'/projects/infrastructure-tracker'},
 {area:'AI & machine learning',status:'Academic & project exploration',detail:'AI/ML coursework and a team project exploring agentic decision support.',tech:['Python','NumPy','Pandas'],evidence:'/projects/cognitive-compass'}
];
export const practiceHours:{area:string;hours:number|null}[]=proficiency.map((p,i)=>({area:p.area,hours:[320,245,185,130][i]}));
