export type Project = { slug:string; name:string; category:string; tagline:string; description:string; stack:string[]; problem:string; solution:string; features:string[]; architecture:string[]; contribution:string; source:string; repo?:string; image?:string; cover?:string; coverAlt?:string; year?:string };
export const personal = {
 name:'Harsha Akasam', fullName:'Sai Surya Sri Harsha Akasam', title:'Software Developer', subtitle:'Full-stack development · Mobile applications · AI / ML',
 intro:'I build web and mobile applications that connect thoughtful interfaces with practical engineering. My work spans React, React Native, REST APIs, and AI-powered experiences.',
 email:'saisuryaakasam@gmail.com', location:'Kakinada, Andhra Pradesh, India', github:'https://github.com/HarshaAkasam', linkedin:'https://www.linkedin.com/in/harsha-akasam-290805ah/', resume:'/assets/harsha-akasam-resume.pdf',
 education:{institution:'Aditya University',degree:'B.Tech · Computer Science (AI & ML)',dates:'2022 — 2026',cgpa:'7.36 / 10',location:'Surampalem, Andhra Pradesh'},
};
export const sections=[['/','Home'],['/about','About'],['/blogs','Blogs'],['/skills','Skills'],['/work','Work'],['/practice','Practice']];
export const skills:Record<string,string[]>={
 'Frontend':['React.js','React Native','HTML5','CSS3','Tailwind CSS','Redux Toolkit','Context API'],
 'Backend':['Node.js','Express.js','REST APIs','Axios','MongoDB','MySQL'],
 'Languages':['Python','Java','JavaScript','TypeScript','C++','C'],
 'AI / ML':['OpenCV','Pandas','NumPy','Machine Learning','Deep Learning','Neural Networks'],
 'Tools':['Git','GitHub','Postman','VS Code','Jupyter Notebook','Linux','Vite'],
 'Coursework':['Data Structures & Algorithms','DBMS','Operating Systems','Computer Networks','Artificial Intelligence','Software Engineering']
};
export const projects:Project[]=[
 {slug:'cognitive-compass',cover:'/assets/project-covers/cognitive-compass.webp',coverAlt:'AI-generated conceptual illustration of a compass and branching decision paths',name:'Cognitive Compass',category:'AI / ML',tagline:'More perspectives. More thoughtful decisions.',description:'A final-year team project exploring agentic AI for structured, reflective personal decision support.',stack:['React.js','Python','Google ADK'],problem:'Generic assistants can offer a single perspective when decisions involve uncertainty, competing priorities, and emotional context.',solution:'The project design separates query understanding, framework matching, and response synthesis to help people examine trade-offs while retaining control of their decisions.',features:['Conversation and decision-query routing','Structured signals for intent, complexity, and ambiguity','Deterministic weighted framework matching','Framework-based decision synthesis','Conversational and educational agent roles'],architecture:['React web interface','Python / Google ADK agent orchestration','Structured framework knowledge library','Model service for response synthesis'],contribution:'Final-year team project with Harsha Akasam as a listed team member. Individual responsibilities are not yet specified.',source:'Final Review presentation supplied by Harsha; architecture described as presented',repo:'https://github.com/Jashprachodai/cognitive-compass',image:'/assets/cognitive-22.png',year:'Final-year project'},
 {slug:'job-align',cover:'/assets/project-covers/job-align.webp',coverAlt:'AI-generated conceptual illustration of a smartphone, resume cards, and a career pathway',name:'Job Align',category:'Mobile',tagline:'Job discovery meets personalized preparation.',description:'A job aggregator mobile application with ATS-based matching and a Dream Job preparation roadmap.',stack:['React Native','Expo','Express.js','MongoDB'],problem:'Job seekers need a convenient way to browse opportunities across platforms and understand how their profiles match a role.',solution:'A mobile client connects to an Express.js and MongoDB backend for job listings, matching, and personalized preparation.',features:['Job aggregation across platforms','ATS-based job matching','Dream Job roadmap and interactive quizzes','API testing with Postman','Lazy loading, caching, and API batching'],architecture:['React Native client','REST endpoints on Express.js','MongoDB storage'],contribution:'Developed mobile functionality, integrated backend APIs, and worked on matching, roadmaps, and performance optimizations, as described in the supplied résumés.',source:'Job Align App.js and package.json verified on GitHub, 9 September 2026; backend and outcome descriptions from supplied résumés',repo:'https://github.com/HarshaAkasam/Job-align',year:'2025'},
 {slug:'infrastructure-tracker',cover:'/assets/project-covers/infrastructure-tracker.webp',coverAlt:'AI-generated conceptual illustration of a campus building and connected assets',name:'Infrastructure Tracker',category:'Web',tagline:'Campus assets, brought into view.',description:'An asset-management project for exploring university infrastructure through asset-wise and hall-wise views.',stack:['React.js','Express.js','MongoDB','JavaScript'],problem:'University infrastructure is difficult to inspect when asset information is scattered across facilities.',solution:'A React interface organizes infrastructure by building, floor, and room, supported by an Express backend and MongoDB. The résumés also document an earlier vanilla JavaScript version.',features:['Building, floor, and room hierarchy','Electrical and non-electrical asset tracking','Usage, warranty, and manufacturer details','Maintenance planning and lifecycle insights','React interfaces connected to MongoDB'],architecture:['React.js interface','Express.js backend','MongoDB database'],contribution:'Developed the React frontend and hierarchy views, integrated MongoDB, and collaborated on data modeling and real-time data views, as documented in the project README.',source:'Project README verified on GitHub, 9 September 2026; supplied résumés',repo:'https://github.com/HarshaAkasam/Infrastructure_Tracker',year:'2024'},
 {slug:'busfinder',cover:'/assets/project-covers/busfinder.webp',coverAlt:'AI-generated conceptual illustration of frontend interface components',name:'BusFinder',category:'Repository',tagline:'A frontend repository to explore.',description:'A frontend repository containing HTML, CSS, and JavaScript interfaces. The current entry page is labeled Recipe Finder; the repository is named BusFinder.',stack:['HTML5','CSS3','JavaScript'],problem:'The intended product scope needs clarification because the repository name and current interface title differ.',solution:'Explore the linked source for the current frontend prototype.',features:[],architecture:[],contribution:'Listed by Harsha as one of his projects.',source:'Repository contents and index.html verified on GitHub, 9 September 2026',repo:'https://github.com/HarshaAkasam/BusFinder'}
];
export const experience=[
 {title:'Full Stack Development with React Native',company:'Technical Hub',dates:'05 May — 28 Jun 2025',description:'Summer internship covering cross-platform development, database management, authentication, authorization, and security.',certificate:'/assets/internship-2025.pdf'},
 {title:'Full Stack / React Native Intern',company:'Technical Hub',dates:'03 Jun — 27 Jul 2024',description:'Worked with HTML, CSS, JavaScript, and Bootstrap, with résumé-described experience in React interfaces, REST APIs, MongoDB, and collaborative development.',certificate:'/assets/internship-2024.pdf'}
];
export const certifications=[
 {title:'Database Foundations Associate',issuer:'Oracle University',date:'06 Aug 2025',file:'/assets/oracle.jpg'},
 {title:'CLA: Programming Essentials in C',issuer:'Cisco Networking Academy / C++ Institute',date:'25 Jan 2023',file:'/assets/c-programming.png'},
 {title:'IT Specialist · Python',issuer:'Pearson',date:'10 May 2023',file:'/assets/python-certificate.pdf'},
 {title:'IT Specialist · HTML and CSS',issuer:'Pearson',date:'08 May 2023',file:'/assets/html-css-certificate.pdf'}
];
export const achievements=[{title:'Top 20 Project Selection',detail:'Job Align · Technical Hub · 2025',source:'Supplied résumés'},{title:'Two-time runner-up',detail:'AI Master Quiz, Veda · 2024–2025',source:'Supplied résumés'}];
export const profiles=[{name:'GitHub',handle:'HarshaAkasam',url:personal.github,description:'Source code & projects'},{name:'LeetCode',handle:'Harsha_Akasam',url:'https://leetcode.com/u/Harsha_Akasam/',description:'Algorithms & problem solving'},{name:'CodeChef',handle:'harsha_akasam',url:'https://www.codechef.com/users/harsha_akasam',description:'Competitive programming'},{name:'GeeksforGeeks',handle:'harsha-akasam29',url:'https://www.geeksforgeeks.org/profile/harsha-akasam29?tab=activity',description:'Data structures & practice'},{name:'HackerRank',handle:'22A91A61D2',url:'https://www.hackerrank.com/profile/22A91A61D2',description:'Programming challenges'}];
